services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: container_monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ../db/docker-init.sql:/docker-entrypoint-initdb.d/docker-init.sql
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ../db/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://admin:password@db:5432/container_monitoring?sslmode=disable", "up" ]
